@extends('app.template.layout-profile')

@section('content')
<div class="container py-4">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h2>💳 Timesheet Payments</h2>
                    <small class="text-muted">View and manage your payment history</small>
                </div>
                @php
                    $userRole = auth()->user()->role->slug ?? '';
                    $isAdmin = auth()->user()->role_id == 1 || $userRole === 'admin';
                @endphp
                @if($isAdmin)
                <div>
                    <button class="btn btn-primary" data-toggle="modal" data-target="#generatePaymentModal">
                        <i class="fa fa-plus"></i> Generate Payment Links
                    </button>
                </div>
                @endif
            </div>

            @if(session('success'))
                <div class="alert alert-success alert-dismissible fade show">
                    {{ session('success') }}
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            @endif

            @if(session('error'))
                <div class="alert alert-danger alert-dismissible fade show">
                    {{ session('error') }}
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            @endif

            <!-- Payment Statistics -->
            <div class="row mb-4">
                <div class="col-md-3">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Payments</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $payments->total() }}</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-left-warning shadow h-100 py-2">
                        <div class="card-body">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                {{ $payments->where('status', 'pending')->count() + $payments->where('status', 'link_sent')->count() }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-left-success shadow h-100 py-2">
                        <div class="card-body">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Paid</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                {{ $payments->where('status', 'paid')->count() }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Paid</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                £{{ number_format($payments->where('status', 'paid')->sum('total_amount'), 2) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Payments Table -->
            <div class="card shadow">
                <div class="card-header">
                    <h5 class="mb-0"><i class="fa fa-list"></i> Payment History</h5>
                </div>
                <div class="card-body">
                    @if($payments->isEmpty())
                        <div class="text-center py-5">
                            <i class="fa fa-credit-card fa-3x text-muted mb-3"></i>
                            <p class="text-muted">
                                @if(!$isAdmin)
                                    No payment links found. Payment links will be generated by administrators and sent to you via notification.
                                @else
                                    No payments found. Generate payment links to get started.
                                @endif
                            </p>
                        </div>
                    @else
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Date</th>
                                        <th>Service Provider</th>
                                        <th>Period</th>
                                        <th>Hours</th>
                                        <th>Amount</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($payments as $payment)
                                        <tr>
                                            <td>{{ $payment->created_at->format('d M Y') }}</td>
                                            <td>
                                                @if($payment->carer)
                                                    {{ $payment->carer->firstname }} {{ substr($payment->carer->lastname ?? '', 0, 1) }}.
                                                    <br>
                                                    <small class="text-muted">{{ $payment->carer->role->title ?? 'N/A' }}</small>
                                                @else
                                                    <span class="text-muted">N/A</span>
                                                @endif
                                            </td>
                                            <td>
                                                {{ $payment->period_start->format('M d') }} - {{ $payment->period_end->format('M d, Y') }}
                                                <br>
                                                <small class="text-muted">{{ ucfirst($payment->period_type) }}</small>
                                            </td>
                                            <td><strong>{{ number_format($payment->total_hours, 2) }}h</strong></td>
                                            <td>
                                                <strong>£{{ number_format($payment->total_amount, 2) }}</strong>
                                                @if($payment->platform_fee > 0)
                                                    <br>
                                                    <small class="text-muted">Fee: £{{ number_format($payment->platform_fee, 2) }}</small>
                                                @endif
                                            </td>
                                            <td>
                                                <span class="badge 
                                                    @if($payment->status == 'paid') badge-success
                                                    @elseif($payment->status == 'pending' || $payment->status == 'link_sent') badge-warning
                                                    @elseif($payment->status == 'failed') badge-danger
                                                    @else badge-secondary
                                                    @endif">
                                                    {{ ucfirst($payment->status) }}
                                                </span>
                                            </td>
                                            <td>
                                                <a href="{{ route('timesheet-payments.show', $payment->id) }}" class="btn btn-sm btn-info">
                                                    <i class="fa fa-eye"></i> View
                                                </a>
                                                @if($payment->status == 'link_sent' && $payment->stripe_payment_link_url)
                                                    <a href="{{ $payment->stripe_payment_link_url }}" target="_blank" class="btn btn-sm btn-success">
                                                        <i class="fa fa-external-link"></i> Pay
                                                    </a>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                        <div class="mt-3">
                            {{ $payments->links() }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@php
    $userRole = auth()->user()->role->slug ?? '';
    $isAdmin = auth()->user()->role_id == 1 || $userRole === 'admin';
@endphp
@if($isAdmin)
<!-- Generate Payment Modal (Admin Only) -->
<div class="modal fade" id="generatePaymentModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ route('timesheet-payments.generate') }}" method="POST">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title">Generate Payment Links</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Client <span class="text-danger">*</span></label>
                        <select name="client_id" class="form-control" required>
                            <option value="">Select Client</option>
                            @foreach(\App\Models\User::where('role_id', 2)->where('status', 'active')->get() as $client)
                                <option value="{{ $client->id }}">{{ $client->firstname }} {{ $client->lastname }} ({{ $client->email }})</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Service Provider (Optional)</label>
                        <select name="carer_id" class="form-control">
                            <option value="">All Service Providers</option>
                            @foreach(\App\Models\User::whereIn('role_id', [3, 4, 5])->where('status', 'active')->get() as $provider)
                                <option value="{{ $provider->id }}">{{ $provider->firstname }} {{ $provider->lastname }} ({{ $provider->role->title ?? 'N/A' }})</option>
                            @endforeach
                        </select>
                        <small class="text-muted">Leave empty to generate for all service providers</small>
                    </div>
                    <div class="form-group">
                        <label>Period Type <span class="text-danger">*</span></label>
                        <select name="period_type" class="form-control" required>
                            <option value="weekly">Weekly</option>
                            <option value="monthly">Monthly</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Period Start (Optional)</label>
                        <input type="date" name="period_start" class="form-control">
                        <small class="text-muted">Leave empty to use current week/month</small>
                    </div>
                    <div class="form-group">
                        <label>Period End (Optional)</label>
                        <input type="date" name="period_end" class="form-control">
                        <small class="text-muted">Leave empty to use current week/month</small>
                    </div>
                    <div class="alert alert-info">
                        <i class="fa fa-info-circle"></i> This will generate payment links for approved timesheets in the selected period. Payment links will be sent to the client via notification.
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Generate Payment Links</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

